let s = `taochen
zhengjie
zhengjie
luq
cht
chenhuiy
shaoqf
chenshaohua
tangjs
hehongyan
jif
chenxu
wanglj
chujp
jinhan
qianzy
zhangzj
wangding
hexiang
yangbo
fhs
xiebin
zhanglg
zhuhx
xjruanzl
ruanzl
xjdengql
dengql
jiaping
qiuyifeng
fuwz
yuanzw
zhengyif
louly
louly
jiangwf
chenhj
chenhj1
zhaods
wangjs
wu_jie
weiry
weiry
qizl
zhujh
zhaowei
qianjb
qianjb
xjqianjb
xuhaofan
wuxj
wangch
yangjian
wxz
rengan
zhangli
nova
tangtao
xiangjie
liyang
tangxin
fuyp
luweimin
luweimin
huanghui
mashouwu_hz
shaoxl
zhouping
lincy
huzhen
hezd
zhongzp
fengbo
zhangqm
pcf
fengxy
weiqiang
chenghong
zhouwq
mayj
tangshl
ljm
fanggq
huzy
dingd
dingd
jyf
lugw
fushenghong
qzjls
zxc
shengw
chenzs
cyq
tzzwj
tzls
tzfys
shi_yy
huhao
wanghr
txwanghr
fangwei
yecy
chenglu
zcjiangjian
zhushijie
anjj
zhanghanliang`
s = s.split('\n')

console.log(s)

let arr = ["taochen", "zhengjie", "zhengjie", "luq", "cht", "chenhuiy", "shaoqf", "chenshaohua", "tangjs", "hehongyan", "jif", "chenxu", "wanglj", "chujp", "jinhan", "qianzy", "zhangzj", "wangding", "hexiang", "yangbo", "fhs", "xiebin", "zhanglg", "zhuhx", "xjruanzl", "ruanzl", "xjdengql", "dengql", "jiaping", "qiuyifeng", "fuwz", "yuanzw", "zhengyif", "louly", "louly", "jiangwf", "chenhj", "chenhj1", "zhaods", "wangjs", "wu_jie", "weiry", "weiry", "qizl", "zhujh", "zhaowei", "qianjb", "qianjb", "xjqianjb", "xuhaofan", "wuxj", "wangch", "yangjian", "wxz", "rengan", "zhangli", "nova", "tangtao", "xiangjie", "liyang", "tangxin", "fuyp", "luweimin", "luweimin", "huanghui", "mashouwu_hz", "shaoxl", "zhouping", "lincy", "huzhen", "hezd", "zhongzp", "fengbo", "zhangqm", "pcf", "fengxy", "weiqiang", "chenghong", "zhouwq", "mayj", "tangshl", "ljm", "fanggq", "huzy", "dingd", "dingd", "jyf", "lugw", "fushenghong", "qzjls", "zxc", "shengw", "chenzs", "cyq", "tzzwj", "tzls", "tzfys", "shi_yy", "huhao", "wanghr",' txwanghr','fangwei','yecy','chenglu','zcjiangjian','zhushijie','anjj','zhanghanliang']